### ISSUE TITLE
Proximo hangs when trying to publish a message

### ISSUE THREAD

**Issue by SpeedyCoder** [uw-labs/proximo#35]
We have seen multiple instances when our producer tried to publish a message and got stuck until the program was restarted. This can be potentially resolved by adding a timeout to the call, but it might an issue with the library.

**Comment by nick-jones** [comment]
We've grabbed stack traces for all goroutines, the 2 pertinent ones are:

```
goroutine 146886 [select, 401 minutes]:
github.com/utilitywarehouse/proximo/proximoc-go.(*ProducerConn).start.func2(0xc00015ff40, 0xc0002de480, 0xc0002de420, 0xc000573710)
	/go/pkg/mod/github.com/utilitywarehouse/proximo@v0.0.1/proximoc-go/client.go:262 +0x34e
created by github.com/utilitywarehouse/proximo/proximoc-go.(*ProducerConn).start
	/go/pkg/mod/github.com/utilitywarehouse/proximo@v0.0.1/proximoc-go/client.go:222 +0x124
```
```
goroutine 146891 [chan send, 394 minutes]:
github.com/utilitywarehouse/proximo/proximoc-go.(*ProducerConn).Produce(0xc00015ff40, 0xc0001e40e0, 0xd3, 0xd3, 0xd3, 0x0)
	/go/pkg/mod/github.com/utilitywarehouse/proximo@v0.0.1/proximoc-go/client.go:179 +0xa3
main.main.func2.1.1(0xc0000323c0, 0x24, 0xbb1540, 0xc000140ca0, 0x2a1f4825, 0xed39962d9, 0x103bae0, 0x0, 0xed395cfe8, 0x103bae0, ...)
	/build/main.go:167 +0x3ce
github.com/utilitywarehouse/***/event.newUnmarshalHandler.func1(0xc000346140, 0x95, 0xa0, 0xc00013b320, 0xc00033c7e0)
	/go/pkg/mod/github.com/utilitywarehouse/***@v0.0.0-20181114134815-c4ddf140470d/event/nats.go:18 +0x12b
github.com/utilitywarehouse/go-pubsub/natss.(*messageSource).ConsumeMessages.func3(0xc000338ba0)
	/go/pkg/mod/github.com/utilitywarehouse/go-pubsub@v0.0.0-20180925092642-d28379a4fe55/natss/source.go:126 +0x86
github.com/nats-io/go-nats-streaming.(*conn).processMsg(0xc0001d1180, 0xc0000b0a50)
	/go/pkg/mod/github.com/nats-io/go-nats-streaming@v0.4.0/stan.go:751 +0x270
github.com/nats-io/go-nats-streaming.(*conn).processMsg-fm(0xc0000b0a50)
	/go/pkg/mod/github.com/nats-io/go-nats-streaming@v0.4.0/sub.go:228 +0x34
github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc000174a00, 0xc0003d4480)
	/go/pkg/mod/github.com/nats-io/go-nats@v1.6.0/nats.go:1778 +0x258
created by github.com/nats-io/go-nats.(*Conn).subscribe
	/go/pkg/mod/github.com/nats-io/go-nats@v1.6.0/nats.go:2517 +0x460
```

(happy to provide the full set if wanted)

We also have set `GRPC_GO_LOG_SEVERITY_LEVEL=info`, so the application has logged various GRPC related details. The line `{"level":"debug","msg":"publishing ***"...}` is logged pre-publish. The code logs after publish, but nothing has been logged in this instance, so it certainly appears to be hung.

```
<snip>
WARNING: 2018/12/05 06:21:38 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:21:38 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:22:14 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:22:15 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:22:15 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:23:29 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
INFO: 2018/12/05 06:23:29 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, READY
INFO: 2018/12/05 06:23:54 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:23:54 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
INFO: 2018/12/05 06:23:54 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, READY
INFO: 2018/12/05 06:23:54 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:23:55 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:23:55 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:23:55 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:23:57 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
INFO: 2018/12/05 06:23:57 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, READY
{"level":"debug","msg":"publishing ***","payload":***","time":"2018-12-05T06:26:09Z"}
INFO: 2018/12/05 06:26:44 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:26:44 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:26:44 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:26:44 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:26:45 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:26:45 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:26:45 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:26:47 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
INFO: 2018/12/05 06:26:47 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, READY
INFO: 2018/12/05 06:28:04 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:04 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:04 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:04 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:05 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:05 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:05 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:07 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:08 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:08 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:10 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:11 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:11 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:14 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:15 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:15 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:20 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:21 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:21 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:31 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:32 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:32 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:28:48 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:28:49 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:28:49 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:29:12 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:29:13 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:29:13 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:29:59 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:30:00 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:30:00 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:31:18 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:31:19 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:31:19 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:33:22 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
WARNING: 2018/12/05 06:33:23 grpc: addrConn.createTransport failed to connect to {***:6868 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp ***:6868: connect: connection refused". Reconnecting...
INFO: 2018/12/05 06:33:23 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, TRANSIENT_FAILURE
INFO: 2018/12/05 06:34:59 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, CONNECTING
INFO: 2018/12/05 06:34:59 pickfirstBalancer: HandleSubConnStateChange: 0xc00001d600, READY
```
